In [146]:
import re
import math
import warnings
import tqdm
import json
import matplotlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import optimize


warnings.filterwarnings("ignore")

In [147]:
data1 = pd.read_excel('2a数据_已替换时间戳_已矫正.xlsx')
with open("best_labels.json", "r") as json_file:
    group_targets = json.load(json_file)
new_column = pd.Series(group_targets["best_labels"], name="组号")
data1 = pd.concat([data1, new_column], axis=1)

In [148]:
data1

,ID,发病到首次影像检查时间间隔,入院首次影像检查流水号,ED_volume.0,随访1流水号,ED_volume.1,随访2流水号,ED_volume.2,随访3流水号,ED_volume.3,...,ED_volume.4,随访5流水号,ED_volume.5,随访6流水号,ED_volume.6,随访7流水号,ED_volume.7,随访8流水号,ED_volume.8,组号
0,sub001,2.5,9000,48919,29766.0,57898.0,475590.0,81747.0,935055.0,107793.0,...,126558.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
1,sub002,3.0,10800,23526,53724.0,23390.0,249199.0,28415.0,1612859.0,34868.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
2,sub003,2.0,7200,32621,34281.0,41292.0,142545.0,49767.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
3,sub004,1.0,3600,22191,61107.0,18956.0,301843.0,9540.0,819004.0,5204.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
4,sub005,5.0,18000,47392,95283.0,23182.0,352595.0,12898.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,sub156,5.5,19800,8968,89575.0,12860.0,452217.0,13716.0,1055942.0,12709.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,sub157,0.5,1800,409,4920.0,3742.0,25620.0,53311.0,72240.0,29545.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,sub158,2.8,10080,17948,66180.0,21099.0,256680.0,44069.0,1111140.0,64243.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,sub159,3.0,10800,14430,95520.0,19019.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,sub160,4.0,14400,18622,62940.0,28683.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [141]:
# 按组号分组
grouped_data = data1.groupby("组号")
grouped_dataframes = {}
for group, group_df in grouped_data:
    grouped_dataframes[group] = group_df.drop(["发病到首次影像检查时间间隔","组号"], axis = 1).reset_index().drop(["index"], axis = 1)

In [142]:
grouped_dataframes[group]

,ID,入院首次影像检查流水号,ED_volume.0,随访1流水号,ED_volume.1,随访2流水号,ED_volume.2,随访3流水号,ED_volume.3,随访4流水号,ED_volume.4,随访5流水号,ED_volume.5,随访6流水号,ED_volume.6,随访7流水号,ED_volume.7,随访8流水号,ED_volume.8
0,sub002,10800,23526,53724.0,23390.0,249199.0,28415.0,1612859.0,34868.0,4029091.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,sub004,3600,22191,61107.0,18956.0,301843.0,9540.0,819004.0,5204.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,sub005,18000,47392,95283.0,23182.0,352595.0,12898.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,sub009,2412,18799,144202.0,22191.0,238178.0,48539.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,sub012,7200,15254,41554.0,16723.0,104632.0,13818.0,257805.0,20788.0,622277.0,22086.0,1732597.0,55714.0,4578517.0,1099.0,NaN,NaN,NaN,NaN
5,sub014,3600,12291,84216.0,19434.0,861131.0,31092.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,sub018,1800,23890,56056.0,38354.0,138317.0,45387.0,849773.0,64084.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,sub019,32400,11107,65955.0,16594.0,153490.0,18649.0,1068844.0,27745.0,2901171.0,1549.0,6423754.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
8,sub020,2412,160,21956.0,527.0,130705.0,233.0,2623363.0,0.0,6005977.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [143]:
# 取XY值
grouped_dataframes_XY = {}
for g in grouped_dataframes:
    x=[]
    y=[]
    ID=[]
    datapp=pd.DataFrame()
    for i in range(len(list(grouped_dataframes[g].columns))):
        if list(grouped_dataframes[g].columns)[i][-3:]=='流水号':
            for j in range(len(grouped_dataframes[g][list(grouped_dataframes[g].columns)[i]])):
                if j <=99 and not math.isnan(grouped_dataframes[g][list(grouped_dataframes[g].columns)[i]][j]) and not math.isnan(grouped_dataframes[g][list(grouped_dataframes[g].columns)[i+1]][j]):
                    x.append(grouped_dataframes[g][list(grouped_dataframes[g].columns)[i]][j]/3600)
                    y.append(grouped_dataframes[g][list(grouped_dataframes[g].columns)[i+1]][j]/1000)
                    ID.append(grouped_dataframes[g]['ID'][j])
    datapp['ID']=ID.copy()
    datapp['X']=x.copy()
    datapp['Y']=y.copy()
    grouped_dataframes_XY[g] = {"datapp": datapp.copy()}

In [145]:
grouped_dataframes_XY

{0.0: {'datapp':         ID            X       Y
  0   sub008     2.000000  14.353
  1   sub010     1.000000  15.272
  2   sub013     3.000000   9.694
  3   sub017     2.000000  11.533
  4   sub023     2.000000  42.734
  5   sub024     5.000000   9.317
  6   sub059     1.000000   1.396
  7   sub078     5.000000   2.679
  8   sub079     1.000000   7.317
  9   sub088    10.000000  23.528
  10  sub093     0.500000   4.923
  11  sub008    10.245556  32.889
  12  sub010    15.000000  22.355
  13  sub013    26.464167   9.249
  14  sub017    14.870278  22.075
  15  sub023    28.161667  44.699
  16  sub024    29.363889   7.296
  17  sub059    46.111389   3.226
  18  sub078    31.239722   0.552
  19  sub079    27.847222   6.525
  20  sub088    34.757500  13.051
  21  sub093     3.577778   3.943
  22  sub008    98.245833  51.887
  23  sub010    39.332500  23.424
  24  sub013   194.313333  15.231
  25  sub017   181.805833  44.436
  26  sub023   221.032222  41.808
  27  sub024   297.228056   1.124
  28  sub059   238.107500   1.488
  29  sub078   200.321111   2.378
  30  sub079   218.690556   9.754
  31  sub088   113.100278  29.340
  32  sub093    25.480556   6.974
  33  sub008   173.525278  34.914
  34  sub010   211.397778  10.274
  35  sub013   513.457778   7.072
  36  sub017   475.707222  34.853
  37  sub023   363.761111  40.009
  38  sub024   460.313889   0.000
  39  sub079   321.576389   1.794
  40  sub093    49.341111   9.355
  41  sub010   951.549444   0.000
  42  sub013   763.466389   1.754
  43  sub023   506.965278  30.197
  44  sub079  1155.191389   0.053
  45  sub093   271.171667   3.258
  46  sub023   656.226111   3.868
  47  sub023  1397.366111   0.377},
 1.0: {'datapp':         ID           X       Y
  0   sub006   24.000000  97.503
  1   sub011    1.000000   5.080
  2   sub042    2.000000  12.949
  3   sub064    1.000000   7.239
  4   sub067    4.000000   4.242
  5   sub070    3.000000   8.178
  6   sub071    2.000000  27.830
  7   sub072    2.000000  10.390
  8   sub075    3.000000  17.633
  9   sub086    3.000000   3.327
  10  sub089    1.500000   9.695
  11  sub092    2.000000   1.084
  12  sub096    1.000000   5.951
  13  sub006   47.874444  95.384
  14  sub011   17.140278   3.642
  15  sub042   25.938889  20.132
  16  sub064    8.055556   4.015
  17  sub067   28.313889   5.065
  18  sub070    9.653333  10.374
  19  sub071   16.260000  33.546
  20  sub072   19.652500  18.574
  21  sub075   13.666111  13.297
  22  sub086   18.411389   1.154
  23  sub089   21.413889  17.750
  24  sub092   11.924722   0.711
  25  sub096   13.761389   6.094
  26  sub006  121.631667  81.745
  27  sub011  332.575556   0.013
  28  sub042  314.538056   3.744
  29  sub064   54.887222   1.169
  30  sub067  127.538611  11.560
  31  sub070  297.957778  15.157
  32  sub071   44.931389   7.538
  33  sub072  186.246944  16.510
  34  sub075   86.403056  42.038
  35  sub086  179.388056   6.076
  36  sub089  283.874167  67.976
  37  sub092   78.772222  38.232
  38  sub096   87.980278   9.911
  39  sub006  172.188056  50.859
  40  sub042  770.527778   0.625
  41  sub064  312.028889   1.736
  42  sub071  208.180278  66.089
  43  sub075  208.602500  34.310
  44  sub086  348.297500   2.490
  45  sub089  542.108611  21.797
  46  sub092  173.574167  52.388
  47  sub096  255.119167  11.687
  48  sub006  285.647778  24.730
  49  sub064  623.949722   0.032
  50  sub071  256.991944  70.518
  51  sub075  927.570833  11.202
  52  sub096  423.501111   0.231
  53  sub064  960.654167   0.000
  54  sub071  928.500556   0.487
  55  sub096  595.642778   0.000},
 2.0: {'datapp':          ID            X       Y
  0    sub001     2.500000  48.919
  1    sub003     2.000000  32.621
  2    sub016     1.000000  28.955
  3    sub021     1.000000  12.852
  4    sub025     7.000000   9.073
  ..      ...          ...     ...
  262  sub060   294.407778  22.092
  263  sub063   978.013333  47.223
  264  sub068  4801.220556   0.000
  265  sub056   457.617500   0.075
  266  sub060   409.010556  20.720

  [267 rows x 3 columns]},
 3.0: {'datapp':         ID            X        Y
  0   sub007    18.000000   32.434
  1   sub015     5.000000    5.759
  2   sub022     1.000000    5.463
  3   sub030     8.000000   18.378
  4   sub035     3.000000   15.345
  5   sub069     2.000000   41.370
  6   sub081     3.000000    1.091
  7   sub091     3.000000    5.318
  8   sub007    44.080278   20.015
  9   sub015   168.373056   17.205
  10  sub022    21.459722    8.707
  11  sub030    33.031667   40.860
  12  sub035    20.874722   21.633
  13  sub069    45.276389   44.764
  14  sub081    27.421667   11.074
  15  sub091    26.086667   11.482
  16  sub007   117.124722   31.287
  17  sub015   335.461944   96.502
  18  sub022   333.572500    8.820
  19  sub030   129.949167  104.295
  20  sub035   110.791667   22.328
  21  sub069   196.167222   30.013
  22  sub081   129.010278   15.033
  23  sub091   145.048056   11.741
  24  sub007   192.694722   42.807
  25  sub015   640.590556   55.312
  26  sub030   297.958611   79.204
  27  sub035   254.615833   12.735
  28  sub069   339.505000   20.900
  29  sub081   319.929722    8.175
  30  sub091   481.416111   10.975
  31  sub007   283.437222   56.867
  32  sub030   465.250278   94.574
  33  sub035   398.882500   14.406
  34  sub069   524.927222   11.519
  35  sub081  4307.572500   72.247
  36  sub007   309.030000   51.531
  37  sub035   591.468056    4.432
  38  sub007   409.509167   43.794},
 4.0: {'datapp':         ID            X       Y
  0   sub002     3.000000  23.526
  1   sub004     1.000000  22.191
  2   sub005     5.000000  47.392
  3   sub009     0.670000  18.799
  4   sub012     2.000000  15.254
  5   sub014     1.000000  12.291
  6   sub018     0.500000  23.890
  7   sub019     9.000000  11.107
  8   sub020     0.670000   0.160
  9   sub002    14.923333  23.390
  10  sub004    16.974167  18.956
  11  sub005    26.467500  23.182
  12  sub009    40.056111  22.191
  13  sub012    11.542778  16.723
  14  sub014    23.393333  19.434
  15  sub018    15.571111  38.354
  16  sub019    18.320833  16.594
  17  sub020     6.098889   0.527
  18  sub002    69.221944  28.415
  19  sub004    83.845278   9.540
  20  sub005    97.943056  12.898
  21  sub009    66.160556  48.539
  22  sub012    29.064444  13.818
  23  sub014   239.203056  31.092
  24  sub018    38.421389  45.387
  25  sub019    42.636111  18.649
  26  sub020    36.306944   0.233
  27  sub002   448.016389  34.868
  28  sub004   227.501111   5.204
  29  sub012    71.612500  20.788
  30  sub018   236.048056  64.084
  31  sub019   296.901111  27.745
  32  sub020   728.711944   0.000
  33  sub002  1119.191944   0.000
  34  sub012   172.854722  22.086
  35  sub019   805.880833   1.549
  36  sub020  1668.326944   0.000
  37  sub012   481.276944  55.714
  38  sub019  1784.376111   0.000
  39  sub012  1271.810278   1.099}}

In [144]:
#线性
def liner_func(x,a,b):
    return a*x+b

#二次
def erchi_func(x,a,b,c):
    return a*x**2+b*x+c

#三次
def sanchi_func(x,a,b,c,d):
    return a*x**3+b*x**2+c*x+d

# 三角函数
def trig_func(x,a,b,c):
    return a*np.sin(x)+b*np.cos(x)+c
# 指数曲线
def target_func(x, a, b, c):
    return a * np.exp(-x / b) + c
# 对数函数
def hyp_func(x, a,b):
    return a*np.log(x)+b

# 定义高斯函数
def gaussian(x, a, b, c):
    return a * np.exp(-(x - b) ** 2 / (2 * c ** 2))

#定义Logistic函数
def logistic(x,a,b,c):
    return  a / (1 + np.exp(-b * (x - c)))


def __sst(y_no_fitting):
    """
    计算SST(total sum of squares) 总平方和
    :param y_no_predicted: List[int] or array[int] 待拟合的y
    :return: 总平方和SST
    """
    y_mean = sum(y_no_fitting) / len(y_no_fitting)
    s_list =[(y - y_mean)**2 for y in y_no_fitting]
    sst = sum(s_list)
    return sst


def __ssr(y_fitting, y_no_fitting):
    """
    计算SSR(regression sum of squares) 回归平方和
    :param y_fitting: List[int] or array[int]  拟合好的y值
    :param y_no_fitting: List[int] or array[int] 待拟合y值
    :return: 回归平方和SSR
    """
    y_mean = sum(y_no_fitting) / len(y_no_fitting)
    s_list =[(y - y_mean)**2 for y in y_fitting]
    ssr = sum(s_list)
    return ssr


def __sse(y_fitting, y_no_fitting):
    """
    计算SSE(error sum of squares) 残差平方和
    :param y_fitting: List[int] or array[int] 拟合好的y值
    :param y_no_fitting: List[int] or array[int] 待拟合y值
    :return: 残差平方和SSE
    """
    s_list = [(y_fitting[i] - y_no_fitting[i])**2 for i in range(len(y_fitting))]
    sse = sum(s_list)
    return sse


def goodness_of_fit(y_fitting, y_no_fitting):
    """
    计算拟合优度R^2
    :param y_fitting: List[int] or array[int] 拟合好的y值
    :param y_no_fitting: List[int] or array[int] 待拟合y值
    :return: 拟合优度R^2
    """
    SSR = __ssr(y_fitting, y_no_fitting)
    SST = __sst(y_no_fitting)
    rr = SSR /SST
    return rr
def selected_func(you,model,model_select):
    maxyou=max(you)
    for s in range(len(you)):
        if you[s]==maxyou:
            
            return model[s],model_select[s]
        
    

def is_non_real(x):
    # 判断复数是否为非实数
    return math.isinf(x) or math.isnan(x)

def sgn(x):
    if x < 0:
        return -1
    elif x == 0:
        return 0
    else:
        return 1
        

# 求解方程 f(x) = y
def solve_equation(f,y):
    equation = lambda x: f(x) - y
    x_initial_guess = 0  # 初始猜测值
    x_solution = fsolve(equation, x_initial_guess)
    return x_solution

for g in grouped_dataframes_XY:
    data=grouped_dataframes_XY[g]['datapp']
    x=data['X']
    y=data['Y']

    Set={}
    youSet={}
    resSet={}
    resTime={}
    you=[]
    model=[]
    model_select=[]
    you_index={}
    RMR=[]
    try:
        a1 = np.polyfit(x, y, 1)#线性
        you1 = goodness_of_fit([liner_func(x[p],a1[0],a1[1]) for p in range(len(x))],y)
        you.append(you1)
        rmr1=[round(liner_func(x[p],a1[0],a1[1])-y[p],4) for p in range(len(x))]
        model.append({'回归类型':'线性回归','回归系数':a1,'残差':rmr1,'ID':ID})
        you_index['线性回归']=you1
        model_select.append((liner_func,a1))
    except:
        pass

    try:
        a2 = np.polyfit(x, y, 2)#二次
        you2 = goodness_of_fit([erchi_func(x[p],a2[0],a2[1],a2[2]) for p in range(len(x))],y)
        rmr2=[round(erchi_func(x[p],a2[0],a2[1],a2[2])-y[p],4) for p in range(len(x))]
        you.append(you2)
        model.append({'回归类型':'二次函数回归','回归系数':a2,'残差':rmr2,'ID':ID})
        you_index['二次函数回归']=you2
        model_select.append((erchi_func,a2))
    except:
        pass

    try:
        a3 = np.polyfit(x, y, 3)#三次
        you3 = goodness_of_fit([sanchi_func(x[p],a3[0],a3[1],a3[2],a3[3]) for p in range(len(x))],y)
        rmr3=[round(sanchi_func(x[p],a3[0],a3[1],a3[2],a3[3])-y[p],4) for p in range(len(x))]
        you.append(you3)
        model.append({'回归类型':'三次函数回归','回归系数':a3,'残差':rmr3,'ID':ID})
        you_index['三次函数回归']=you3
        model_select.append((sanchi_func,a3))
    except:
        pass

    #拟合三角函数模型
    try:
        a4,_=optimize.curve_fit(trig_func,x,y)
        you4 = goodness_of_fit([trig_func(x[p],a4[0],a4[1],a4[2]) for p in range(len(x))],y)
        rmr4=[round(trig_func(x[p],a4[0],a4[1],a4[2])-y[p],4) for p in range(len(x))]
        you.append(you4)
        model.append({'回归类型':'三角函数回归','回归系数':a4,'残差':rmr4,'ID':ID})
        you_index['三角函数回归']=you4
        model_select.append((trig_func,a4))

    except:
        pass

    #拟合指数函数模型
    try:
        a5,_=optimize.curve_fit(target_func,x,y)
        you5 = goodness_of_fit([target_func(x[p], a5[0], a5[1], a5[2]) for p in range(len(x))],y)
        rmr5=[round(target_func(x[p], a5[0], a5[1], a5[2])-y[p],4) for p in range(len(x))]
        you.append(you5)
        model.append({'回归类型':'指数函数回归','回归系数':a5,'残差':rmr5,'ID':ID})
        you_index['指数函数回归']=you5
        model_select.append((target_func,a5))
    except:
        pass

    #拟合对数函数模型
    try:
        a6,_=optimize.curve_fit(hyp_func,x,y)
        you6 = goodness_of_fit([hyp_func(x[p], a6[0],a6[1]) for p in range(len(x))],y)
        rmr6=[round(hyp_func(x[p], a6[0],a6[1])-y[p],4) for p in range(len(x))]
        you.append(you6)
        model.append({'回归类型':'对数函数回归','回归系数':a6,'残差':rmr6,'ID':ID})
        you_index['对数函数回归']=you6
        model_select.append((hyp_func,a6))
    except:
        pass
    try:
        popt, pcov = optimize.curve_fit(gaussian, x, y)
        # 提取拟合参数
        a_fit, b_fit, c_fit = popt

        you7 = goodness_of_fit([gaussian(x[p], a_fit,b_fit,c_fit) for p in range(len(x))],y)
        rmr7=[round(gaussian(x[p], a_fit,b_fit,c_fit)-y[p],4) for p in range(len(x))]
        you.append(you7)
        model.append({'回归类型':'高斯函数回归','回归系数':popt,'残差':rmr7,'ID':ID})
        you_index['高斯函数回归']=you7
        model_select.append((gaussian,popt))
    except:
        pass

    try:
        popt, pcov = optimize.curve_fit(logistic, x, y)
        # 提取拟合参数
        a_fit, b_fit, c_fit = popt
        you8 = goodness_of_fit([logistic(x[p], a_fit,b_fit,c_fit) for p in range(len(x))],y)

        rmr8=[round(logistic(x[p], a_fit,b_fit,c_fit)-y[p],4) for p in range(len(x))]
        you.append(you8)
        model.append({'回归类型':'logistic函数回归','回归系数':popt,'残差':rmr8,'ID':ID})
        you_index['logistic函数回归']=you8
        model_select.append((logistic,popt))

    except:
        pass

    # model=[f'线性回归，系数为{a1}',f'二次函数回归，系数为{a2}',f'三次函数回归，系数为{a3}',f'三角函数回归，系数为{a4}',f'指数函数回归，系数为{a5}',f'对数函数回归，系数为{a6}']
    res,model_=selected_func(you,model,model_select)

    # Set[index]=res#选择函数模型，例如：1用三角函数
    # youSet[index]=you_index#拟合优度

    print(you_index)
    p=0 #取最大
    for i in range(len(list(you_index.keys()))):
        if you_index[list(you_index.keys())[i]]>you_index[list(you_index.keys())[p]]:
            p=i

    print(model[p])
    ID=model[p]['ID']
    RMR=model[p]['残差']
    SET_RMR={}
    for i in range(len(ID)):
        SET_RMR[ID[i]]=[]
    for i in range(len(ID)):
        SET_RMR[ID[i]].append(model[p]['残差'][i])
    datasave=pd.DataFrame(columns=['ID','残差'])
    datasave['ID']=SET_RMR.keys()
    datasave['残差']=SET_RMR.values()
    datasave.to_excel(f'Q22填表答案_向量结果_{g}.xlsx',index=False)
    datasave['残差']=datasave['残差'].apply(lambda x: sum(x) / len(x))
    datasave.to_excel(f'Q22填表答案_单值结果_{g}.xlsx',index=False)

{'线性回归': 0.057132792262263456, '二次函数回归': 0.07462673914341282, '三次函数回归': 0.10627076216752833, '三角函数回归': 0.03671540632047492, '指数函数回归': 0.019713591438636775, '对数函数回归': 0.00023245405690029483, '高斯函数回归': 0.5173604309340998, 'logistic函数回归': 1.1545708254504762e-20}
{'回归类型': '高斯函数回归', '回归系数': array([18.97817648, 18.19277866, 18.32229878]), '残差': [-1.5105, -3.0525, 3.7631, 1.3095, -29.8915, 5.3274, 10.8235, 11.9654, 4.9025, -6.3553, 6.9832, -15.6147, -3.6628, 7.8906, -3.4063, -28.3319, 8.4632, 2.718, 14.1762, 9.9932, -0.4394, 9.8637, -51.8856, -13.6698, -15.231, -44.436, -41.808, -1.124, -1.488, -2.378, -9.754, -29.34, 10.5608, -34.914, -10.274, -7.072, -34.853, -40.009, 0.0, -1.794, -4.8811, 0.0, -1.754, -30.197, -0.053, -3.258, -3.868, -0.377], 'ID': ['sub002', 'sub004', 'sub005', 'sub009', 'sub012', 'sub014', 'sub018', 'sub019', 'sub020', 'sub002', 'sub004', 'sub005', 'sub009', 'sub012', 'sub014', 'sub018', 'sub019', 'sub020', 'sub002', 'sub004', 'sub005', 'sub009', 'sub012', 'sub014', 'sub018', 'sub019', 'sub020', 'sub002', 'sub004', 'sub012', 'sub018', 'sub019', 'sub020', 'sub002', 'sub012', 'sub019', 'sub020', 'sub012', 'sub019', 'sub012']}
{'线性回归': 0.02460526695211298, '二次函数回归': 0.07032559403783796, '三次函数回归': 0.17981249968844062, '三角函数回归': 0.0019302457129511399, '指数函数回归': 3.659820501223965e-17, '对数函数回归': 0.016582844711810537, '高斯函数回归': 0.258496225897089, 'logistic函数回归': 0.08237838458704867}
{'回归类型': '高斯函数回归', '回归系数': array([ 44.29362464, 166.87317763, 106.53804294]), '残差': [-79.4804, 8.1015, 0.4259, 5.9425, 9.5248, 5.392, -14.4551, 2.9849, -4.063, 10.243, 3.583, 12.2909, 7.2305, -71.6469, 12.8555, -1.6671, 10.5661, 13.9478, 4.5351, -17.2395, -1.5253, 2.4531, 15.6213, -0.3097, 14.6711, 9.6764, -41.2703, 13.2014, 13.2066, 24.3238, 29.8153, 5.621, 15.4691, 27.0573, -8.737, 37.9131, -43.7407, -6.7655, 23.7608, -6.6205, -0.625, 15.7722, -25.0026, 6.713, 7.9005, -21.7073, -8.1819, 19.744, -0.9371, -0.0275, -39.5461, -11.202, 2.2034, 0.0, -0.487, 0.0135], 'ID': ['sub002', 'sub004', 'sub005', 'sub009', 'sub012', 'sub014', 'sub018', 'sub019', 'sub020', 'sub002', 'sub004', 'sub005', 'sub009', 'sub012', 'sub014', 'sub018', 'sub019', 'sub020', 'sub002', 'sub004', 'sub005', 'sub009', 'sub012', 'sub014', 'sub018', 'sub019', 'sub020', 'sub002', 'sub004', 'sub012', 'sub018', 'sub019', 'sub020', 'sub002', 'sub012', 'sub019', 'sub020', 'sub012', 'sub019', 'sub012']}
{'线性回归': 0.013235636512400542, '二次函数回归': 0.03627173975351114, '三次函数回归': 0.09244864653615742, '三角函数回归': 0.0009840132083286015, '指数函数回归': 0.06909093043330684, '对数函数回归': 0.04118292970535723, '高斯函数回归': 0.13904228602972815, 'logistic函数回归': 3.3635272223144695e-19}
{'回归类型': '高斯函数回归', '回归系数': array([ 49.25101722, 481.09174776, 400.42560773]), '残差': [-24.808, -8.5459, -4.9518, 11.1512, 15.3625, 2.9082, 16.861, 7.5071, -20.3992, 6.6282, 23.2931, 22.8633, 13.0092, 7.44, 4.1141, 19.6172, 7.9361, 19.6022, 18.8342, 3.6491, -1.7767, 17.5951, -13.6598, 18.2271, 19.5302, 20.6975, 15.8023, 7.4901, 17.1831, 7.3111, 11.3752, 8.5862, -5.6619, 15.9053, 13.1735, -9.6368, 8.8032, 13.95, 17.0275, -20.9989, 4.1988, 9.3941, 20.1011, -5.2789, 13.8851, 15.0721, 12.1321, -9.8338, 1.3265, 20.8231, -29.6238, 23.6411, -5.5389, 16.6241, 10.8052, 13.92, -15.757, 14.494, 16.6002, -33.3708, -16.674, -11.3726, 7.0371, 8.2859, 5.6799, -14.8317, -1.7001, -35.4636, -11.4148, 20.1887, 19.4657, -9.1235, -8.3042, -15.0343, 14.3643, -1.9605, 8.5426, 18.2779, -2.4167, -13.4339, 15.4878, -15.8331, 16.2898, -5.892, 21.8375, 14.9984, -0.7607, -17.7584, 3.5608, 9.0715, -11.053, -7.8777, 16.5355, 6.6119, -19.247, 3.3204, 12.2122, 16.8137, -13.2612, -14.8479, 3.3447, 19.1247, -16.7459, 12.9837, -6.6666, 11.6505, -2.6797, -12.9768, 13.5312, -22.8988, 23.3521, -51.4393, 10.368, -58.3813, 17.6185, -1.9546, 5.693, 20.427, -48.0588, -22.9482, -61.3031, 12.2459, 1.3682, -14.6454, 13.1159, -10.9668, 2.8352, -19.5967, 36.113, 6.3723, -48.4073, 25.411, -30.6578, 3.3055, -18.7098, -6.2024, 13.333, 4.8721, -30.8021, 5.1338, 8.6508, 12.8463, -14.7469, 30.2507, 23.9781, 34.5568, -36.0567, -9.5, 13.072, -12.9484, -8.2323, 35.4503, 11.4063, -13.1176, -28.1062, 15.2051, 7.1361, -14.3689, -6.595, -16.0168, 27.5897, -29.2358, 17.0396, 4.7913, 37.4077, 7.4169, -14.2681, 5.4377, -33.298, 39.3865, 19.2048, 13.2128, -68.2538, 35.2037, 11.2275, -3.8974, 35.1175, -65.5205, 25.5236, -8.1074, 23.3091, -34.1861, 10.4053, 12.6049, -30.6588, 13.6224, -3.0311, 10.9515, -29.0503, -1.0554, 45.2657, 15.7006, -43.1191, 13.5676, 23.742, -29.1225, 42.4993, 42.1827, -23.7705, 27.2848, 22.2641, -0.3917, -8.8408, -40.5819, -19.4823, -1.3161, 7.6034, -7.5936, -46.3105, 24.1851, -9.1536, 0.1463, -20.5869, 44.4828, 35.6795, 33.8148, -123.1476, 7.3726, -77.7787, 3.3228, 46.623, 28.3353, 8.1048, 20.1519, -83.8486, -50.8785, -9.3715, 7.9046, 0.2662, 9.3675, -4.4006, -51.3292, -18.9861, 29.7294, -7.0056, -58.3401, 40.7204, 7.9034, -2.1648, 20.3678, 0.0, 0.0, -76.8533, 10.9557, 32.5482, -66.5197, -6.4642, -0.057, 0.0, 8.9908, -6.5761, -67.193, -0.5073, 0.0119, -23.649, 30.4925, 14.7029, 37.7535, 8.0061, -94.0399, -0.451, 43.2929, 22.0871, -24.4196, 0.0, 49.0915, 27.7395], 'ID': ['sub002', 'sub004', 'sub005', 'sub009', 'sub012', 'sub014', 'sub018', 'sub019', 'sub020', 'sub002', 'sub004', 'sub005', 'sub009', 'sub012', 'sub014', 'sub018', 'sub019', 'sub020', 'sub002', 'sub004', 'sub005', 'sub009', 'sub012', 'sub014', 'sub018', 'sub019', 'sub020', 'sub002', 'sub004', 'sub012', 'sub018', 'sub019', 'sub020', 'sub002', 'sub012', 'sub019', 'sub020', 'sub012', 'sub019', 'sub012']}
{'线性回归': 0.09186809144639022, '二次函数回归': 0.1223857076632305, '三次函数回归': 0.17466118208786363, '三角函数回归': 0.0006414221481113329, '指数函数回归': 0.14118795465155567, '对数函数回归': 0.15528009578269497, '高斯函数回归': 0.1395475297678999, 'logistic函数回归': 8.71599084331821e-19}
{'回归类型': '三次函数回归', '回归系数': array([ 4.90664548e-08, -2.42931718e-04,  1.48907770e-01,  1.66938607e+01]), '残差': [-13.1382, 11.6733, 11.3795, -0.5084, 1.7934, -24.3793, 16.0474, 11.8204, 2.7749, 17.9081, 11.071, -19.5108, -1.9361, -21.8216, 9.5215, 8.9319, -0.4061, -55.3412, 32.3354, -72.2454, 7.9484, 6.9137, 16.9336, 21.5904, -6.0887, -30.0197, -38.4112, 26.934, 20.2677, 32.9004, 26.5778, -16.3662, -56.2439, 26.1464, 23.4982, 0.0091, -10.572, 25.5028, -3.4906], 'ID': ['sub002', 'sub004', 'sub005', 'sub009', 'sub012', 'sub014', 'sub018', 'sub019', 'sub020', 'sub002', 'sub004', 'sub005', 'sub009', 'sub012', 'sub014', 'sub018', 'sub019', 'sub020', 'sub002', 'sub004', 'sub005', 'sub009', 'sub012', 'sub014', 'sub018', 'sub019', 'sub020', 'sub002', 'sub004', 'sub012', 'sub018', 'sub019', 'sub020', 'sub002', 'sub012', 'sub019', 'sub020', 'sub012', 'sub019', 'sub012']}

IndexError: list index out of range